# 1.Print 'Hello HCIA'.

In [3]:
print('Hello HCIA')

Hello HCIA


# 2.Define two variables and calculate their sum.

In [4]:
a = 2
b = 3
print(a+b)

5


# 3.Define a list and replicate in three different ways.

In [31]:
#1
import copy
c = [1,2,3,4]
n = 1000
output = [copy.deepcopy(c) for i in range(n)]
#2
d = ['1','2','3','4']
output = [d]*1000
#3
e=[1,2,3]
[e]*10


[[1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3],
 [1, 2, 3]]

# 4.Define two lists and merge them together.

In [32]:
g=['1','2','3']
h=['2','5']
print(g+h)

['1', '2', '3', '2', '5']


# 5. Get the last element of the list and print it.

In [16]:
test_list = [1, 4, 5, 6, 3, 5] 
print ("The original list is : " + str(test_list)) 
for i in range(0, len(test_list)): 
  
    if i == (len(test_list)-1): 
        print ("The last element of list using loop : "
                                  +  str(test_list[i])) 

The original list is : [1, 4, 5, 6, 3, 5]
The last element of list using loop : 5


# 6.Define a tuple that contains only one element.

In [2]:
p=(1)
print(p)

1


# 7.Define a three-line long string.

In [36]:
s = ("trhee-line"
" long "
"string"
)
print(s)

trhee-line long string


# 8.Define a tuple and then use the 'for loop' to print all the elements.

In [14]:
k = (1, 2, 3, 4, 5)
for i in range(5):
    print(k[i])

1
2
3
4
5


# 9.Define a function to do Multiplication, such as Mul(8,6),and its output 48.

In [15]:
def multiply(numbers):
    total = 1
    for x in numbers:
        total *=x
        return total
    print(multiply(24,2))

# 10.Import numpy and use numpy to define an array, the its shape  is (5,5) and all its elements is 0.

In [1]:
import numpy
numpy.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 11.Import numpy and use numpy to define an array, the shape is (4,6) and all elements is 0.

In [3]:
import numpy
numpy.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 12.Use numpy.arrange() to generate an array of shape(15,), then modify the shape to(3,5).

In [3]:
import numpy as np
v = np.arange(15.)
w = np.zeros((3,5))
v = v.reshape(w.shape)
print(v)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]


# 13.Define two matrices, then calculate and print the result of their point multiplication.

In [14]:
import numpy
a=numpy.arange(2,8).reshape(2,3)
print('a= ',a)
b=numpy.full((3,3),4)
print('b= ', b)
print('a*b= ',numpy.dot(a, b))

a=  [[2 3 4]
 [5 6 7]]
b=  [[4 4 4]
 [4 4 4]
 [4 4 4]]
a*b=  [[36 36 36]
 [72 72 72]]
